apiVersion: v2
name: idp
description: A Helm chart for Internal Developer Platform (IDP)
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/your-org/idp
sources:
  - https://github.com/your-org/idp
maintainers:
  - name: Platform Team
    email: platform@yourcompany.com
keywords:
  - developer-platform
  - self-service
  - automation
  - django
  - kubernetes

dependencies:
  - name: postgresql
    version: "12.12.10"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "18.6.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled

annotations:
  category: Developer Tools
  licenses: MIT 
