apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "idp.fullname" . }}-celery-beat
  labels:
    {{- include "idp.celeryBeat.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.celeryBeat }}
  selector:
    matchLabels:
      {{- include "idp.celeryBeat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "idp.celeryBeat.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "idp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: celery-beat
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "idp.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - celery
            - -A
            - idp
            - beat
            - --loglevel=info
            - --scheduler=django_celery_beat.schedulers:DatabaseScheduler
          envFrom:
            - configMapRef:
                name: {{ include "idp.fullname" . }}-config
            - secretRef:
                name: {{ include "idp.fullname" . }}-secret
          resources:
            {{- toYaml .Values.resources.celeryBeat | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 
