apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "idp.fullname" . }}-config
  labels:
    {{- include "idp.labels" . | nindent 4 }}
data:
  # Django settings
  DEBUG: {{ .Values.env.DEBUG | quote }}
  ALLOWED_HOSTS: {{ .Values.env.ALLOWED_HOSTS | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.env.CORS_ALLOWED_ORIGINS | quote }}
  
  # Database settings
  DB_NAME: {{ include "idp.postgresql.database" . | quote }}
  DB_USER: {{ include "idp.postgresql.username" . | quote }}
  DB_HOST: {{ include "idp.postgresql.host" . | quote }}
  DB_PORT: {{ include "idp.postgresql.port" . | quote }}
  
  # Redis settings
  REDIS_URL: {{ include "idp.redis.url" . | quote }}
  
  # Monitoring
  PROMETHEUS_METRICS_ENABLED: {{ .Values.env.PROMETHEUS_METRICS_ENABLED | quote }}
  
  {{- range $key, $value := .Values.configMap.additionalConfig }}
  {{ $key }}: {{ $value | quote }}
  {{- end }} 
