apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "idp.fullname" . }}-flower
  labels:
    {{- include "idp.flower.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.flower }}
  selector:
    matchLabels:
      {{- include "idp.flower.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "idp.flower.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "idp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: flower
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "idp.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - celery
            - -A
            - idp
            - flower
            - --port=5555
          ports:
            - name: http
              containerPort: 5555
              protocol: TCP
          env:
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "idp.fullname" . }}-config
                  key: REDIS_URL
          resources:
            {{- toYaml .Values.resources.flower | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 
