{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "idp.fullname" . }}-role
  labels:
    {{- include "idp.labels" . | nindent 4 }}
rules:
{{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "idp.fullname" . }}-rolebinding
  labels:
    {{- include "idp.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "idp.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "idp.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }} 
