apiVersion: v1
kind: Secret
metadata:
  name: {{ include "idp.fullname" . }}-secret
  labels:
    {{- include "idp.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secrets.secretKey | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  {{- range $key, $value := .Values.secrets.additionalSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }} 
