apiVersion: v1
kind: Service
metadata:
  name: {{ include "idp.fullname" . }}-web
  labels:
    {{- include "idp.web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: {{ .Values.service.web.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "idp.web.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "idp.fullname" . }}-flower
  labels:
    {{- include "idp.flower.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.flower.port }}
      targetPort: {{ .Values.service.flower.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "idp.flower.selectorLabels" . | nindent 4 }} 
